apps:
  - name: kamihimedb
    script: dist/index.js
    watch:
      - dist
    ignore_watch:
      - dist/views
      - dist/static
    env:
      NODE_ENV: development
    env_production:
      NODE_ENV: production
